/**
 * Loads the Blender-authored camera compositions.
 *
 * Blender remains the visual composition source of truth: `previs.json` is
 * generated by `blender/previs/export_cameras.py` from the actual camera
 * objects in `blender/dancefloor-previs.blend`. Do not hand-edit the JSON —
 * move the camera in Blender and re-export, or the next export overwrites it.
 */

import type { ActId, SectionId } from '$content/types';
import previs from './previs.json';
import type { CameraComposition, CameraKeyframe, Vec3 } from './types';

interface PrevisKeyframe {
	anchor: string;
	act: string;
	section: string;
	at: number;
	position: number[];
	target: number[];
	fov: number;
}

interface PrevisClass {
	master: string;
	aspect: number;
	keyframes: PrevisKeyframe[];
}

const asVec3 = (v: number[]): Vec3 => [v[0], v[1], v[2]];

function toKeyframe(kf: PrevisKeyframe): CameraKeyframe {
	return {
		anchor: kf.anchor,
		act: kf.act as ActId,
		section: kf.section as SectionId,
		at: kf.at,
		position: asVec3(kf.position),
		target: asVec3(kf.target),
		fov: kf.fov
	};
}

/**
 * Scroll length per class. This is a narrative decision rather than a camera
 * one — mobile must not preserve desktop scroll distance — so it lives here
 * and not in the Blender export.
 */
const SCROLL_VH: Record<string, number> = {
	desktop: 1000,
	tablet: 800,
	mobile: 650
};

/** Pointer parallax is desktop-only: never emulate hover on touch. */
const PARALLAX: Record<string, number> = {
	desktop: 0.35,
	tablet: 0,
	mobile: 0
};

function build(name: string): CameraComposition {
	const source = (previs.classes as Record<string, PrevisClass>)[name];
	if (!source) throw new Error(`No previs composition for "${name}"`);
	return {
		master: source.master,
		keyframes: source.keyframes.map(toKeyframe),
		parallax: PARALLAX[name] ?? 0,
		scrollVh: SCROLL_VH[name] ?? 1000
	};
}

export const CAMERA_DESKTOP = build('desktop');
export const CAMERA_TABLET = build('tablet');
export const CAMERA_MOBILE = build('mobile');
